### PR TITLE
Use mkdocs and add gitpod configuration

### LINKED ISSUE #22: [Feature Request]: Use `mkdocs`
### Code of Conduct

- [X] #30

### Potential Enhancement

Especially if we're going to publish to PyPi (#21), we should provide some sort of documentation. An easy way to generate this is [`mkdocs`](https://www.mkdocs.org), especially with [`mkdocstrings`](https://mkdocstrings.github.io/) to auto-generate documentation from the code itself.

### How it could be implemented

Covered above, but [`mkdocs`](https://pypi.org/project/mkdocs) and the plugin [`mkdocstrings`](https://pypi.org/project/mkdocstrings).

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by osfanbuff63**
Resolves #22.

Adds `mkdocs` using the `material` theme, and `mkdocstrings`
to auto-generate references from the code.

This also adds an actions workflow to deploy the docs to Pages whenever a commit to `main` is pushed. You may need to enable Pages and set it to deploy using GitHub Actions, but this might be done automatically with [`actions/configure-pages`](https://github.com/actions/configure-pages).

In addition, I've added a [gitpod](https://gitpod.io) configuration.

I've made this a PR as it's quite big, so just to not throw anyone else off this is a different branch.

### CODE REVIEW

**Review by nsde — CHANGES_REQUESTED** [review]
I don't know about the last change with the main.py. Maybe we should except both? Is the exception type OS-dependent?

Apart from that, LGTM.

**Comment by osfanbuff63** [comment]
> I don't know about the last change with the main.py. Maybe we should except both? Is the exception type OS-dependent?
> 
> Apart from that, LGTM.

The `OSError` class is the base for both `WinError` and probably something similar for Unix-based systems. The `FileNotFoundError` should be derived from `OSError` so we should be fine, but that's a change for another day I guess.

**Comment by osfanbuff63** [comment]
@nsde should we just merge this or do you have anything else to say?

**Comment by nsde** [comment]
> @nsde should we just merge this or do you have anything else to say?

I dunno

**Pull request merged**
