### PR TITLE
Improve the Linux/MacOS auto install scripts, once again

### PR DESCRIPTION
**Pull request by RaptaG**

### CODE REVIEW

**Comment by RaptaG** [comment]
@nsde, merge (?)

**Comment by nsde** [comment]
> @nsde, merge (?)

Okay, if everything's done, I'll merge :)

**Comment by nsde** [comment]
I can't *actually* merge, so I'm just gonna do this manually :)

**Review by nsde — COMMENTED** [review]
LGTM

**Comment by RaptaG** [comment]
> I can't actually merge, so I'm just gonna do this manually :)

:concernedtater:

**Comment by Madis0** [comment]
> I can't _actually_ merge, so I'm just gonna do this manually :)

Why not? You should have pull request rights.

**Comment by nsde** [comment]
> Why not? You should have pull request rights.

It's not about the permission. There was a merge conflict.

**Comment by Madis0** [comment]
Well that can be solved here as well 😛

**Pull request closed without merging**
