### PR TITLE
Add OpenDyslexic font option and include fonts

### PR DESCRIPTION
**Pull request by tuxinal**
* GitHub token related functions are removed as they are no longer used
* Fonts are now declared through stylesheets to avoid bugs in some cases

NOT tested on windows yet. please make sure it works there properly if you can.

### CODE REVIEW

**Review by osfanbuff63 — COMMENTED** [review]
For some reason, the fonts seem to be backward? Not entirely sure why though.

**Comment by tuxinal** [comment]
wdym by backwards exactly? mirrored? written in the wrong direction? can you send a screenshot?

**Comment by osfanbuff63** [comment]
Like when the font is set to Inter, it uses OpenDyslexic (I think). Or, maybe it doesn't want to use OpenDyslexic and is defaulting to some font that I'm not sure of?

Correction: The latter appears to be true. ~~Maybe it's because I don't have the OpenDyslexic font installed? If that's the case, probably not an issue.~~ **Edit:** This didn't change anything... not honestly sure what's happening here.
 
Here's some screenshots:
image
image

**Comment by tuxinal** [comment]
@osfanbuff63 can you test this commit on windows? you'd have to run `pyside6-rcc vanilla_installer/assets/fonts.qrc -o vanilla_installer/fonts.py` in the root directory first. this would have to be added as a step in CI too.

**Comment by osfanbuff63** [comment]
Alright, can do. Won't be able to test for a few hours but I can do it when I can.

**Comment by osfanbuff63** [comment]
Alright - this works...mostly!

This is opendyslexic for sure:
OpenDyslexic font

For some reason, the font needed to be `Inter Regular` to work (not sure why tbh) - but given that this is included now I don't think it'll be an issue. Could someone on Linux test?

**Comment by osfanbuff63** [comment]
(also the commits are unverified because I forgot to change my email in git lol)

**Comment by tuxinal** [comment]
huh inter regular doesn't work on linux _or at least not for me_

**Comment by osfanbuff63** [comment]
Hmm - guess we'll need to pull a `platform.platform()` lol

**Comment by tuxinal** [comment]
I'm gonna try to see why the names are different on different platforms first.
If I couldn't find anything then we don't really have a choice

**Comment by tuxinal** [comment]
Someone should test this commit on mac. other than that it _should in theory_ work properly on windows and linux.

**Review by osfanbuff63 — APPROVED** [review]
I'll go ahead and approve this - if we can get a Mac tester that's great but a lot of this software needs testing on macOS anyway 😅

**Comment by osfanbuff63** [comment]
(i'll test again before I merge though)

**Review by osfanbuff63 — APPROVED** [review]
Tested again on Windows - still works. I think that waiting for a macOS tester might take a bit (given that it doesn't compile and I don't know why xD) but :blobfoxshrug:

**Comment by osfanbuff63** [comment]
mostly merging this so that i dont have to set up more remotes in a new git repo xd

**Pull request merged**
